name: ci-cd

on:
  push:
    branches:
      - master

jobs:
  BUILD_IMAGE:
    runs-on: "ubuntu-latest"
    steps:
      - name: LOGIN TO DOCKER
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v2
      - name: BUILD THE IMAGE
        run: "docker build -t dnyaneshwar89/docker-react -f Dockerfile.dev ."
      - name: RUN ALL TESTS
        run: docker run -e CI=true dnyaneshwar89/docker-react npm run test -- --coverage
